version: '3.6'

services:
  postgres-service:
    container_name: postgres_service_tris
    image: postgres:14-alpine
    ports:
      - '5439:5439'
    environment:
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_DB=postgres
    restart: on-failure
    networks:
      - default
    command: -p 5439
